### ISSUE TITLE
`depth(0)` ignores `/dist` directory

### ISSUE THREAD

**Issue by BeAllAround** [senecajs/seneca-maintain#11]
There are going to be plugins where the main js file isn't at the top level dir. For example, if we have `dist/notion-provider.js` Seneca Maintain is gonna throw "entry not found" even though the file is there. This is because it doesn't actually see it because of the `depth(0)`.

This also happens with Typescript source files in `/src`

Here is a suggested solution:

here: https://github.com/senecajs/seneca-maintain/blob/main/maintain.js#L133

use: `.paths(process.cwd(), process.cwd() + '/dist', process.cwd() + '/src')`

No need to set `depth` to 1 - that would be bug-prone.

here is some sort of pseudocode

```
subDirs = [ process.cwd() + '/dist', process.cwd() + '/src' ]
subDirs = subDirs.filter(dir => exists(dir) )
```

then
`.paths(process.cwd(), ...subDirs )`

**Comment by rionastokes** [comment]
Just published an update that should solve this, both to github and npm - please check it out and let me know if the problem is resolved!
